///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Project1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Project1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c778f625-b014-42c7-9b6b-927a42bcaacf")]
    public partial class Project1Repository : RepoGenBaseFolder
    {
        static Project1Repository instance = new Project1Repository();
        Project1RepositoryFolders.MBATestAppFolder _mbatest;

        /// <summary>
        /// Gets the singleton class instance representing the Project1Repository element repository.
        /// </summary>
        [RepositoryFolder("c778f625-b014-42c7-9b6b-927a42bcaacf")]
        public static Project1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Project1Repository() 
            : base("Project1Repository", "/", null, 0, false, "c778f625-b014-42c7-9b6b-927a42bcaacf", ".\\RepositoryImages\\Project1Repositoryc778f625.rximgres")
        {
            _mbatest = new Project1RepositoryFolders.MBATestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c778f625-b014-42c7-9b6b-927a42bcaacf")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MBATest folder.
        /// </summary>
        [RepositoryFolder("9c13c1af-028c-43a1-a74a-4b6fe0c0e6fa")]
        public virtual Project1RepositoryFolders.MBATestAppFolder MBATest
        {
            get { return _mbatest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Project1RepositoryFolders
    {
        /// <summary>
        /// The MBATestAppFolder folder.
        /// </summary>
        [RepositoryFolder("9c13c1af-028c-43a1-a74a-4b6fe0c0e6fa")]
        public partial class MBATestAppFolder : RepoGenBaseFolder
        {
            Project1RepositoryFolders.LoginFolder _login;

            /// <summary>
            /// Creates a new MBATest  folder.
            /// </summary>
            public MBATestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MBATest", "/dom[@domain='ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "9c13c1af-028c-43a1-a74a-4b6fe0c0e6fa", "")
            {
                _login = new Project1RepositoryFolders.LoginFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c13c1af-028c-43a1-a74a-4b6fe0c0e6fa")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c13c1af-028c-43a1-a74a-4b6fe0c0e6fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login folder.
            /// </summary>
            [RepositoryFolder("ecf138eb-bdb3-4790-9005-b114c3f2a7ec")]
            public virtual Project1RepositoryFolders.LoginFolder Login
            {
                get { return _login; }
            }
        }

        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("ecf138eb-bdb3-4790-9005-b114c3f2a7ec")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputusernameInfo;
            RepoItemInfo _inputpasswordInfo;
            RepoItemInfo _btnsubmitInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 30000, null, false, "ecf138eb-bdb3-4790-9005-b114c3f2a7ec", "")
            {
                _inputusernameInfo = new RepoItemInfo(this, "InputUsername", ".//input[@name='username']", ".//input[#'input-username']", 30000, null, "c13b0ccb-c40b-4eb7-85c5-dc82baee3c1e");
                _inputpasswordInfo = new RepoItemInfo(this, "InputPassword", ".//input[@name='password']", "element", 30000, null, "8d241989-955c-4dc6-8e9f-f1f21dd95cf7");
                _btnsubmitInfo = new RepoItemInfo(this, "BtnSubmit", ".//button[@type='submit']", "element", 30000, null, "8defa89f-f5a3-401d-b1eb-83c0ab6a1135");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ecf138eb-bdb3-4790-9005-b114c3f2a7ec")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ecf138eb-bdb3-4790-9005-b114c3f2a7ec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputUsername item.
            /// </summary>
            [RepositoryItem("c13b0ccb-c40b-4eb7-85c5-dc82baee3c1e")]
            public virtual Ranorex.InputTag InputUsername
            {
                get
                {
                    return _inputusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputUsername item info.
            /// </summary>
            [RepositoryItemInfo("c13b0ccb-c40b-4eb7-85c5-dc82baee3c1e")]
            public virtual RepoItemInfo InputUsernameInfo
            {
                get
                {
                    return _inputusernameInfo;
                }
            }

            /// <summary>
            /// The InputPassword item.
            /// </summary>
            [RepositoryItem("8d241989-955c-4dc6-8e9f-f1f21dd95cf7")]
            public virtual Ranorex.InputTag InputPassword
            {
                get
                {
                    return _inputpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPassword item info.
            /// </summary>
            [RepositoryItemInfo("8d241989-955c-4dc6-8e9f-f1f21dd95cf7")]
            public virtual RepoItemInfo InputPasswordInfo
            {
                get
                {
                    return _inputpasswordInfo;
                }
            }

            /// <summary>
            /// The BtnSubmit item.
            /// </summary>
            [RepositoryItem("8defa89f-f5a3-401d-b1eb-83c0ab6a1135")]
            public virtual Ranorex.Button BtnSubmit
            {
                get
                {
                    return _btnsubmitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("8defa89f-f5a3-401d-b1eb-83c0ab6a1135")]
            public virtual RepoItemInfo BtnSubmitInfo
            {
                get
                {
                    return _btnsubmitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
