///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MBA_Add_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MBA_Add_ProductRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("60343597-5569-4ffd-97cd-459420b48449")]
    public partial class MBA_Add_ProductRepository : RepoGenBaseFolder
    {
        static MBA_Add_ProductRepository instance = new MBA_Add_ProductRepository();
        MBA_Add_ProductRepositoryFolders.MBAFolder _mba;

        /// <summary>
        /// Gets the singleton class instance representing the MBA_Add_ProductRepository element repository.
        /// </summary>
        [RepositoryFolder("60343597-5569-4ffd-97cd-459420b48449")]
        public static MBA_Add_ProductRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MBA_Add_ProductRepository() 
            : base("MBA_Add_ProductRepository", "/", null, 0, false, "60343597-5569-4ffd-97cd-459420b48449", ".\\RepositoryImages\\MBA_Add_ProductRepository60343597.rximgres")
        {
            _mba = new MBA_Add_ProductRepositoryFolders.MBAFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("60343597-5569-4ffd-97cd-459420b48449")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MBA folder.
        /// </summary>
        [RepositoryFolder("b8fab15e-d68c-4af6-b9a5-a354b4e09038")]
        public virtual MBA_Add_ProductRepositoryFolders.MBAFolder MBA
        {
            get { return _mba; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MBA_Add_ProductRepositoryFolders
    {
        /// <summary>
        /// The MBAFolder folder.
        /// </summary>
        [RepositoryFolder("b8fab15e-d68c-4af6-b9a5-a354b4e09038")]
        public partial class MBAFolder : RepoGenBaseFolder
        {
            MBA_Add_ProductRepositoryFolders.LoginPageAppFolder _loginpage;
            MBA_Add_ProductRepositoryFolders.ProfileAppFolder _profile;

            /// <summary>
            /// Creates a new MBA  folder.
            /// </summary>
            public MBAFolder(RepoGenBaseFolder parentFolder) :
                    base("MBA", "", parentFolder, 0, null, false, "b8fab15e-d68c-4af6-b9a5-a354b4e09038", "")
            {
                _loginpage = new MBA_Add_ProductRepositoryFolders.LoginPageAppFolder(this);
                _profile = new MBA_Add_ProductRepositoryFolders.ProfileAppFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b8fab15e-d68c-4af6-b9a5-a354b4e09038")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("a2b631be-3b26-4c42-a339-4d258a3f9224")]
            public virtual MBA_Add_ProductRepositoryFolders.LoginPageAppFolder LoginPage
            {
                get { return _loginpage; }
            }

            /// <summary>
            /// The Profile folder.
            /// </summary>
            [RepositoryFolder("5943608e-67af-4b55-9c8a-4397f7417329")]
            public virtual MBA_Add_ProductRepositoryFolders.ProfileAppFolder Profile
            {
                get { return _profile; }
            }
        }

        /// <summary>
        /// The LoginPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("a2b631be-3b26-4c42-a339-4d258a3f9224")]
        public partial class LoginPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputnameInfo;
            RepoItemInfo _inputpasswordInfo;
            RepoItemInfo _clicksubmitbuttonInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "/dom[@domain='ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "a2b631be-3b26-4c42-a339-4d258a3f9224", "")
            {
                _inputnameInfo = new RepoItemInfo(this, "InputName", ".//input[@id='input-username']", "element", 30000, null, "7182fbe0-c304-4bb8-ad99-8cbbbfcfccef");
                _inputpasswordInfo = new RepoItemInfo(this, "InputPassword", ".//input[@id='input-password']", "element", 30000, null, "4b8ccd5f-f761-4579-afc6-ea1c08e7f8b0");
                _clicksubmitbuttonInfo = new RepoItemInfo(this, "ClickSubmitButton", ".//button[@type='submit']", "element", 30000, null, "985d9302-eee1-444f-8f71-b9e46e285060");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a2b631be-3b26-4c42-a339-4d258a3f9224")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a2b631be-3b26-4c42-a339-4d258a3f9224")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputName item.
            /// </summary>
            [RepositoryItem("7182fbe0-c304-4bb8-ad99-8cbbbfcfccef")]
            public virtual Ranorex.InputTag InputName
            {
                get
                {
                    return _inputnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputName item info.
            /// </summary>
            [RepositoryItemInfo("7182fbe0-c304-4bb8-ad99-8cbbbfcfccef")]
            public virtual RepoItemInfo InputNameInfo
            {
                get
                {
                    return _inputnameInfo;
                }
            }

            /// <summary>
            /// The InputPassword item.
            /// </summary>
            [RepositoryItem("4b8ccd5f-f761-4579-afc6-ea1c08e7f8b0")]
            public virtual Ranorex.InputTag InputPassword
            {
                get
                {
                    return _inputpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPassword item info.
            /// </summary>
            [RepositoryItemInfo("4b8ccd5f-f761-4579-afc6-ea1c08e7f8b0")]
            public virtual RepoItemInfo InputPasswordInfo
            {
                get
                {
                    return _inputpasswordInfo;
                }
            }

            /// <summary>
            /// The ClickSubmitButton item.
            /// </summary>
            [RepositoryItem("985d9302-eee1-444f-8f71-b9e46e285060")]
            public virtual Ranorex.Button ClickSubmitButton
            {
                get
                {
                    return _clicksubmitbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ClickSubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("985d9302-eee1-444f-8f71-b9e46e285060")]
            public virtual RepoItemInfo ClickSubmitButtonInfo
            {
                get
                {
                    return _clicksubmitbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ProfileAppFolder folder.
        /// </summary>
        [RepositoryFolder("5943608e-67af-4b55-9c8a-4397f7417329")]
        public partial class ProfileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _profileInfo;
            RepoItemInfo _avatarInfo;

            /// <summary>
            /// Creates a new Profile  folder.
            /// </summary>
            public ProfileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Profile", "/dom[@domain='ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "5943608e-67af-4b55-9c8a-4397f7417329", "")
            {
                _profileInfo = new RepoItemInfo(this, "Profile", ".//a[@innertext='Auto Auto ']", "element", 30000, null, "e3bd463d-a1f9-4dde-bfec-00f369c890d1");
                _avatarInfo = new RepoItemInfo(this, "Avatar", ".//img[@title='auto']", "element", 30000, null, "13c80e91-969a-4bc8-8c35-1b7de991b2ca");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5943608e-67af-4b55-9c8a-4397f7417329")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5943608e-67af-4b55-9c8a-4397f7417329")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Profile item.
            /// </summary>
            [RepositoryItem("e3bd463d-a1f9-4dde-bfec-00f369c890d1")]
            public virtual Ranorex.ATag Profile
            {
                get
                {
                    return _profileInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Profile item info.
            /// </summary>
            [RepositoryItemInfo("e3bd463d-a1f9-4dde-bfec-00f369c890d1")]
            public virtual RepoItemInfo ProfileInfo
            {
                get
                {
                    return _profileInfo;
                }
            }

            /// <summary>
            /// The Avatar item.
            /// </summary>
            [RepositoryItem("13c80e91-969a-4bc8-8c35-1b7de991b2ca")]
            public virtual Ranorex.ImgTag Avatar
            {
                get
                {
                    return _avatarInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Avatar item info.
            /// </summary>
            [RepositoryItemInfo("13c80e91-969a-4bc8-8c35-1b7de991b2ca")]
            public virtual RepoItemInfo AvatarInfo
            {
                get
                {
                    return _avatarInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
