///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("5d46077b-9b84-4cd6-b80c-e0ffea4372c1")]
    public partial class MyTest1Repository : RepoGenBaseFolder
    {
        static MyTest1Repository instance = new MyTest1Repository();
        MyTest1RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTest1RepositoryFolders.DropdownAppFolder _dropdown;
        MyTest1RepositoryFolders.GoogleTranslateAppFolder _googletranslate;
        MyTest1RepositoryFolders.TaskSwitchingAppFolder _taskswitching;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("5d46077b-9b84-4cd6-b80c-e0ffea4372c1")]
        public static MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest1Repository() 
            : base("MyTest1Repository", "/", null, 0, false, "5d46077b-9b84-4cd6-b80c-e0ffea4372c1", ".\\RepositoryImages\\MyTest1Repository5d46077b.rximgres")
        {
            _applicationundertest = new MyTest1RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _dropdown = new MyTest1RepositoryFolders.DropdownAppFolder(this);
            _googletranslate = new MyTest1RepositoryFolders.GoogleTranslateAppFolder(this);
            _taskswitching = new MyTest1RepositoryFolders.TaskSwitchingAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5d46077b-9b84-4cd6-b80c-e0ffea4372c1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("680abd71-1982-4293-abd4-9717f5a0318b")]
        public virtual MyTest1RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("48c4cc6a-947e-4e6b-bfb1-c6ef0e50e635")]
        public virtual MyTest1RepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }

        /// <summary>
        /// The GoogleTranslate folder.
        /// </summary>
        [RepositoryFolder("f40d24c3-d899-42e6-81c7-896ce247be4d")]
        public virtual MyTest1RepositoryFolders.GoogleTranslateAppFolder GoogleTranslate
        {
            get { return _googletranslate; }
        }

        /// <summary>
        /// The TaskSwitching folder.
        /// </summary>
        [RepositoryFolder("448e0ad6-47f2-4981-95ce-e3d7ba5f8b05")]
        public virtual MyTest1RepositoryFolders.TaskSwitchingAppFolder TaskSwitching
        {
            get { return _taskswitching; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest1RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("680abd71-1982-4293-abd4-9717f5a0318b")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputusernameInfo;
            RepoItemInfo _inputpasswordInfo;
            RepoItemInfo _buttontagloginInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "680abd71-1982-4293-abd4-9717f5a0318b", "")
            {
                _inputusernameInfo = new RepoItemInfo(this, "InputUsername", ".//input[#'input-username']", ".//input[#'input-username']", 30000, null, "993acf24-df7c-44ff-8799-9057b8f8958f");
                _inputpasswordInfo = new RepoItemInfo(this, "InputPassword", ".//input[#'input-password']", ".//input[#'input-password']", 30000, null, "e142b66a-6b49-46a2-97b6-2a5e916137d3");
                _buttontagloginInfo = new RepoItemInfo(this, "ButtonTagLogin", ".//button[@type='submit']", ".//div[#'content']//button[@innertext=' Login']", 30000, null, "ae13ff2a-3004-425e-b099-bd7a84f45e0e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("680abd71-1982-4293-abd4-9717f5a0318b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("680abd71-1982-4293-abd4-9717f5a0318b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputUsername item.
            /// </summary>
            [RepositoryItem("993acf24-df7c-44ff-8799-9057b8f8958f")]
            public virtual Ranorex.InputTag InputUsername
            {
                get
                {
                    return _inputusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputUsername item info.
            /// </summary>
            [RepositoryItemInfo("993acf24-df7c-44ff-8799-9057b8f8958f")]
            public virtual RepoItemInfo InputUsernameInfo
            {
                get
                {
                    return _inputusernameInfo;
                }
            }

            /// <summary>
            /// The InputPassword item.
            /// </summary>
            [RepositoryItem("e142b66a-6b49-46a2-97b6-2a5e916137d3")]
            public virtual Ranorex.InputTag InputPassword
            {
                get
                {
                    return _inputpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPassword item info.
            /// </summary>
            [RepositoryItemInfo("e142b66a-6b49-46a2-97b6-2a5e916137d3")]
            public virtual RepoItemInfo InputPasswordInfo
            {
                get
                {
                    return _inputpasswordInfo;
                }
            }

            /// <summary>
            /// The ButtonTagLogin item.
            /// </summary>
            [RepositoryItem("ae13ff2a-3004-425e-b099-bd7a84f45e0e")]
            public virtual Ranorex.ButtonTag ButtonTagLogin
            {
                get
                {
                    return _buttontagloginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagLogin item info.
            /// </summary>
            [RepositoryItemInfo("ae13ff2a-3004-425e-b099-bd7a84f45e0e")]
            public virtual RepoItemInfo ButtonTagLoginInfo
            {
                get
                {
                    return _buttontagloginInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("48c4cc6a-947e-4e6b-bfb1-c6ef0e50e635")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "48c4cc6a-947e-4e6b-bfb1-c6ef0e50e635", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("48c4cc6a-947e-4e6b-bfb1-c6ef0e50e635")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("48c4cc6a-947e-4e6b-bfb1-c6ef0e50e635")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The GoogleTranslateAppFolder folder.
        /// </summary>
        [RepositoryFolder("f40d24c3-d899-42e6-81c7-896ce247be4d")]
        public partial class GoogleTranslateAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new GoogleTranslate  folder.
            /// </summary>
            public GoogleTranslateAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GoogleTranslate", "/dom[@domain='translate.google.com']", parentFolder, 30000, null, false, "f40d24c3-d899-42e6-81c7-896ce247be4d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f40d24c3-d899-42e6-81c7-896ce247be4d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f40d24c3-d899-42e6-81c7-896ce247be4d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The TaskSwitchingAppFolder folder.
        /// </summary>
        [RepositoryFolder("448e0ad6-47f2-4981-95ce-e3d7ba5f8b05")]
        public partial class TaskSwitchingAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new TaskSwitching  folder.
            /// </summary>
            public TaskSwitchingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TaskSwitching", "/form[@title='Task Switching']", parentFolder, 30000, null, true, "448e0ad6-47f2-4981-95ce-e3d7ba5f8b05", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("448e0ad6-47f2-4981-95ce-e3d7ba5f8b05")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("448e0ad6-47f2-4981-95ce-e3d7ba5f8b05")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
