///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MBA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MBARepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("78c7ad2f-0848-4a48-ace6-93d730985df3")]
    public partial class MBARepository : RepoGenBaseFolder
    {
        static MBARepository instance = new MBARepository();
        MBARepositoryFolders.MBAAppFolder _mba;

        /// <summary>
        /// Gets the singleton class instance representing the MBARepository element repository.
        /// </summary>
        [RepositoryFolder("78c7ad2f-0848-4a48-ace6-93d730985df3")]
        public static MBARepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MBARepository() 
            : base("MBARepository", "/", null, 0, false, "78c7ad2f-0848-4a48-ace6-93d730985df3", ".\\RepositoryImages\\MBARepository78c7ad2f.rximgres")
        {
            _mba = new MBARepositoryFolders.MBAAppFolder(this);
        }

#region Variables

        string _Menu_items = "catalog";

        /// <summary>
        /// Gets or sets the value of variable Menu_items.
        /// </summary>
        [TestVariable("28c71b04-e866-4174-a4d8-859a8fc84df4")]
        public string Menu_items
        {
            get { return _Menu_items; }
            set { _Menu_items = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("78c7ad2f-0848-4a48-ace6-93d730985df3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MBA folder.
        /// </summary>
        [RepositoryFolder("1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb")]
        public virtual MBARepositoryFolders.MBAAppFolder MBA
        {
            get { return _mba; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MBARepositoryFolders
    {
        /// <summary>
        /// The MBAAppFolder folder.
        /// </summary>
        [RepositoryFolder("1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb")]
        public partial class MBAAppFolder : RepoGenBaseFolder
        {
            MBARepositoryFolders.LoginPageFolder _loginpage;
            MBARepositoryFolders.ProfileFolder _profile;
            MBARepositoryFolders.DashboardFolder _dashboard;
            MBARepositoryFolders.LogoutPageFolder _logoutpage;

            /// <summary>
            /// Creates a new MBA  folder.
            /// </summary>
            public MBAAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MBA", "/dom[@domain='ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb", "")
            {
                _loginpage = new MBARepositoryFolders.LoginPageFolder(this);
                _profile = new MBARepositoryFolders.ProfileFolder(this);
                _dashboard = new MBARepositoryFolders.DashboardFolder(this);
                _logoutpage = new MBARepositoryFolders.LogoutPageFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("a75c7191-3d25-4d92-bf61-ca3ad44ecb5e")]
            public virtual MBARepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }

            /// <summary>
            /// The Profile folder.
            /// </summary>
            [RepositoryFolder("a40e102f-ce3a-4343-bcff-b804047e7eaa")]
            public virtual MBARepositoryFolders.ProfileFolder Profile
            {
                get { return _profile; }
            }

            /// <summary>
            /// The Dashboard folder.
            /// </summary>
            [RepositoryFolder("2e537fe2-5dfd-47d7-8b93-6de6bd32d3b5")]
            public virtual MBARepositoryFolders.DashboardFolder Dashboard
            {
                get { return _dashboard; }
            }

            /// <summary>
            /// The LogoutPage folder.
            /// </summary>
            [RepositoryFolder("ccd151c2-bef1-453f-9f43-6fd4798a0144")]
            public virtual MBARepositoryFolders.LogoutPageFolder LogoutPage
            {
                get { return _logoutpage; }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("a75c7191-3d25-4d92-bf61-ca3ad44ecb5e")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputnameInfo;
            RepoItemInfo _inputpasswordInfo;
            RepoItemInfo _clicksubmitbuttonInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 0, null, false, "a75c7191-3d25-4d92-bf61-ca3ad44ecb5e", "")
            {
                _inputnameInfo = new RepoItemInfo(this, "InputName", ".//input[@id='input-username']", "element", 30000, null, "7182fbe0-c304-4bb8-ad99-8cbbbfcfccef");
                _inputpasswordInfo = new RepoItemInfo(this, "InputPassword", ".//input[@id='input-password']", "element", 30000, null, "4b8ccd5f-f761-4579-afc6-ea1c08e7f8b0");
                _clicksubmitbuttonInfo = new RepoItemInfo(this, "ClickSubmitButton", ".//button[@type='submit']", "element", 30000, null, "985d9302-eee1-444f-8f71-b9e46e285060");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a75c7191-3d25-4d92-bf61-ca3ad44ecb5e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputName item.
            /// </summary>
            [RepositoryItem("7182fbe0-c304-4bb8-ad99-8cbbbfcfccef")]
            public virtual Ranorex.InputTag InputName
            {
                get
                {
                    return _inputnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputName item info.
            /// </summary>
            [RepositoryItemInfo("7182fbe0-c304-4bb8-ad99-8cbbbfcfccef")]
            public virtual RepoItemInfo InputNameInfo
            {
                get
                {
                    return _inputnameInfo;
                }
            }

            /// <summary>
            /// The InputPassword item.
            /// </summary>
            [RepositoryItem("4b8ccd5f-f761-4579-afc6-ea1c08e7f8b0")]
            public virtual Ranorex.InputTag InputPassword
            {
                get
                {
                    return _inputpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPassword item info.
            /// </summary>
            [RepositoryItemInfo("4b8ccd5f-f761-4579-afc6-ea1c08e7f8b0")]
            public virtual RepoItemInfo InputPasswordInfo
            {
                get
                {
                    return _inputpasswordInfo;
                }
            }

            /// <summary>
            /// The ClickSubmitButton item.
            /// </summary>
            [RepositoryItem("985d9302-eee1-444f-8f71-b9e46e285060")]
            public virtual Ranorex.Button ClickSubmitButton
            {
                get
                {
                    return _clicksubmitbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ClickSubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("985d9302-eee1-444f-8f71-b9e46e285060")]
            public virtual RepoItemInfo ClickSubmitButtonInfo
            {
                get
                {
                    return _clicksubmitbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ProfileFolder folder.
        /// </summary>
        [RepositoryFolder("a40e102f-ce3a-4343-bcff-b804047e7eaa")]
        public partial class ProfileFolder : RepoGenBaseFolder
        {
            RepoItemInfo _profileInfo;
            RepoItemInfo _avatarInfo;

            /// <summary>
            /// Creates a new Profile  folder.
            /// </summary>
            public ProfileFolder(RepoGenBaseFolder parentFolder) :
                    base("Profile", "", parentFolder, 0, null, false, "a40e102f-ce3a-4343-bcff-b804047e7eaa", "")
            {
                _profileInfo = new RepoItemInfo(this, "Profile", ".//a[@innertext='Auto Auto ']", "element", 30000, null, "e3bd463d-a1f9-4dde-bfec-00f369c890d1");
                _avatarInfo = new RepoItemInfo(this, "Avatar", ".//img[@title='auto']", "element", 30000, null, "13c80e91-969a-4bc8-8c35-1b7de991b2ca");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a40e102f-ce3a-4343-bcff-b804047e7eaa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Profile item.
            /// </summary>
            [RepositoryItem("e3bd463d-a1f9-4dde-bfec-00f369c890d1")]
            public virtual Ranorex.ATag Profile
            {
                get
                {
                    return _profileInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Profile item info.
            /// </summary>
            [RepositoryItemInfo("e3bd463d-a1f9-4dde-bfec-00f369c890d1")]
            public virtual RepoItemInfo ProfileInfo
            {
                get
                {
                    return _profileInfo;
                }
            }

            /// <summary>
            /// The Avatar item.
            /// </summary>
            [RepositoryItem("13c80e91-969a-4bc8-8c35-1b7de991b2ca")]
            public virtual Ranorex.ImgTag Avatar
            {
                get
                {
                    return _avatarInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Avatar item info.
            /// </summary>
            [RepositoryItemInfo("13c80e91-969a-4bc8-8c35-1b7de991b2ca")]
            public virtual RepoItemInfo AvatarInfo
            {
                get
                {
                    return _avatarInfo;
                }
            }
        }

        /// <summary>
        /// The DashboardFolder folder.
        /// </summary>
        [RepositoryFolder("2e537fe2-5dfd-47d7-8b93-6de6bd32d3b5")]
        public partial class DashboardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _atagmenucatalogInfo;
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new Dashboard  folder.
            /// </summary>
            public DashboardFolder(RepoGenBaseFolder parentFolder) :
                    base("Dashboard", "", parentFolder, 0, null, false, "2e537fe2-5dfd-47d7-8b93-6de6bd32d3b5", "")
            {
                _atagmenucatalogInfo = new RepoItemInfo(this, "ATagMenuCatalog", ".//li[@id<'menu-'+$Menu_items]", "", 30000, null, "ee83cfd2-9220-4307-92a7-1545a3e5f64c");
                _newitemInfo = new RepoItemInfo(this, "NewItem", ".//li[#'menu-catalog']/a[@innertext=' Catalog']", ".//li[#'menu-catalog']/a[@innertext=' Catalog']", 30000, null, "993d6cd2-3b7d-4450-9ade-e3e8e82b3330");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2e537fe2-5dfd-47d7-8b93-6de6bd32d3b5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ATagMenuCatalog item.
            /// </summary>
            [RepositoryItem("ee83cfd2-9220-4307-92a7-1545a3e5f64c")]
            public virtual Ranorex.LiTag ATagMenuCatalog
            {
                get
                {
                    return _atagmenucatalogInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The ATagMenuCatalog item info.
            /// </summary>
            [RepositoryItemInfo("ee83cfd2-9220-4307-92a7-1545a3e5f64c")]
            public virtual RepoItemInfo ATagMenuCatalogInfo
            {
                get
                {
                    return _atagmenucatalogInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("993d6cd2-3b7d-4450-9ade-e3e8e82b3330")]
            public virtual Ranorex.ATag NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("993d6cd2-3b7d-4450-9ade-e3e8e82b3330")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }
        }

        /// <summary>
        /// The LogoutPageFolder folder.
        /// </summary>
        [RepositoryFolder("ccd151c2-bef1-453f-9f43-6fd4798a0144")]
        public partial class LogoutPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new LogoutPage  folder.
            /// </summary>
            public LogoutPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LogoutPage", "", parentFolder, 0, null, false, "ccd151c2-bef1-453f-9f43-6fd4798a0144", "")
            {
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//span[@innertext='Logout']", "element", 30000, null, "3cffb199-a1e5-44fc-9d17-46d7aff2f36e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ccd151c2-bef1-453f-9f43-6fd4798a0144")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("3cffb199-a1e5-44fc-9d17-46d7aff2f36e")]
            public virtual Ranorex.SpanTag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("3cffb199-a1e5-44fc-9d17-46d7aff2f36e")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
