///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MBA_WEB
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MBA_WEBRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8413f6b0-199c-49a6-a138-b680566ce355")]
    public partial class MBA_WEBRepository : RepoGenBaseFolder
    {
        static MBA_WEBRepository instance = new MBA_WEBRepository();
        MBA_WEBRepositoryFolders.MBAAppFolder _mba;

        /// <summary>
        /// Gets the singleton class instance representing the MBA_WEBRepository element repository.
        /// </summary>
        [RepositoryFolder("8413f6b0-199c-49a6-a138-b680566ce355")]
        public static MBA_WEBRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MBA_WEBRepository() 
            : base("MBA_WEBRepository", "/", null, 0, false, "8413f6b0-199c-49a6-a138-b680566ce355", ".\\RepositoryImages\\MBA_WEBRepository8413f6b0.rximgres")
        {
            _mba = new MBA_WEBRepositoryFolders.MBAAppFolder(this);
        }

#region Variables

        string _Menu_items = "Catalog";

        /// <summary>
        /// Gets or sets the value of variable Menu_items.
        /// </summary>
        [TestVariable("4867845e-b962-4cec-bf28-0eb7d883f9c6")]
        public string Menu_items
        {
            get { return _Menu_items; }
            set { _Menu_items = value; }
        }

        string _Item = "Products";

        /// <summary>
        /// Gets or sets the value of variable Item.
        /// </summary>
        [TestVariable("cd5e6953-dee2-4952-8036-76ee18e1d77e")]
        public string Item
        {
            get { return _Item; }
            set { _Item = value; }
        }

        string _LabelCheckBox = "Default";

        /// <summary>
        /// Gets or sets the value of variable LabelCheckBox.
        /// </summary>
        [TestVariable("ff5877dd-ef87-4d44-9a83-48cd35fcd76b")]
        public string LabelCheckBox
        {
            get { return _LabelCheckBox; }
            set { _LabelCheckBox = value; }
        }

        string _containerDasboard = "Total Orders";

        /// <summary>
        /// Gets or sets the value of variable containerDasboard.
        /// </summary>
        [TestVariable("86a68477-9096-4e74-8c17-12d2036ae670")]
        public string containerDasboard
        {
            get { return _containerDasboard; }
            set { _containerDasboard = value; }
        }

        string _CustomerName = "";

        /// <summary>
        /// Gets or sets the value of variable CustomerName.
        /// </summary>
        [TestVariable("e0e6960b-7239-4160-8d60-94679ce4e862")]
        public string CustomerName
        {
            get { return _CustomerName; }
            set { _CustomerName = value; }
        }

        string _Variable = "Value";

        /// <summary>
        /// Gets or sets the value of variable Variable.
        /// </summary>
        [TestVariable("329a1ad6-d378-48d4-8a5c-c4c9d8e63f1d")]
        public string Variable
        {
            get { return _Variable; }
            set { _Variable = value; }
        }

        string _ProductName = "Samsung Galaxy S10 5G 256GB (Majestic Black)";

        /// <summary>
        /// Gets or sets the value of variable ProductName.
        /// </summary>
        [TestVariable("493e42c9-b5d3-4317-8d17-d06182eed869")]
        public string ProductName
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8413f6b0-199c-49a6-a138-b680566ce355")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MBA folder.
        /// </summary>
        [RepositoryFolder("1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb")]
        public virtual MBA_WEBRepositoryFolders.MBAAppFolder MBA
        {
            get { return _mba; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MBA_WEBRepositoryFolders
    {
        /// <summary>
        /// The MBAAppFolder folder.
        /// </summary>
        [RepositoryFolder("1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb")]
        public partial class MBAAppFolder : RepoGenBaseFolder
        {
            MBA_WEBRepositoryFolders.LoginPageFolder _loginpage;
            MBA_WEBRepositoryFolders.ProfileFolder _profile;
            MBA_WEBRepositoryFolders.DashboardFolder _dashboard;
            MBA_WEBRepositoryFolders.LogoutPageFolder _logoutpage;
            MBA_WEBRepositoryFolders.NavigationFolder _navigation;
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new MBA  folder.
            /// </summary>
            public MBAAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MBA", "/dom[@domain='ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb", "")
            {
                _loginpage = new MBA_WEBRepositoryFolders.LoginPageFolder(this);
                _profile = new MBA_WEBRepositoryFolders.ProfileFolder(this);
                _dashboard = new MBA_WEBRepositoryFolders.DashboardFolder(this);
                _logoutpage = new MBA_WEBRepositoryFolders.LogoutPageFolder(this);
                _navigation = new MBA_WEBRepositoryFolders.NavigationFolder(this);
                _newitemInfo = new RepoItemInfo(this, "NewItem", ".//*[text()<$ProductName]//ancestor::tr//input[@type='checkbox']", "", 30000, null, "55cc26c6-1425-47cb-afad-e1e0ee6c5ef6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1ce3a6bd-83d8-4593-9ce7-9bbb7264cefb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("55cc26c6-1425-47cb-afad-e1e0ee6c5ef6")]
            public virtual Ranorex.InputTag NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("55cc26c6-1425-47cb-afad-e1e0ee6c5ef6")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("a75c7191-3d25-4d92-bf61-ca3ad44ecb5e")]
            public virtual MBA_WEBRepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }

            /// <summary>
            /// The Profile folder.
            /// </summary>
            [RepositoryFolder("a40e102f-ce3a-4343-bcff-b804047e7eaa")]
            public virtual MBA_WEBRepositoryFolders.ProfileFolder Profile
            {
                get { return _profile; }
            }

            /// <summary>
            /// The Dashboard folder.
            /// </summary>
            [RepositoryFolder("2e537fe2-5dfd-47d7-8b93-6de6bd32d3b5")]
            public virtual MBA_WEBRepositoryFolders.DashboardFolder Dashboard
            {
                get { return _dashboard; }
            }

            /// <summary>
            /// The LogoutPage folder.
            /// </summary>
            [RepositoryFolder("ccd151c2-bef1-453f-9f43-6fd4798a0144")]
            public virtual MBA_WEBRepositoryFolders.LogoutPageFolder LogoutPage
            {
                get { return _logoutpage; }
            }

            /// <summary>
            /// The Navigation folder.
            /// </summary>
            [RepositoryFolder("8573a4d7-4ef9-4099-a278-3c38386bd62c")]
            public virtual MBA_WEBRepositoryFolders.NavigationFolder Navigation
            {
                get { return _navigation; }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("a75c7191-3d25-4d92-bf61-ca3ad44ecb5e")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputnameInfo;
            RepoItemInfo _inputpasswordInfo;
            RepoItemInfo _clicksubmitbuttonInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 0, null, false, "a75c7191-3d25-4d92-bf61-ca3ad44ecb5e", "")
            {
                _inputnameInfo = new RepoItemInfo(this, "InputName", ".//input[@id='input-username']", "element", 30000, null, "7182fbe0-c304-4bb8-ad99-8cbbbfcfccef");
                _inputpasswordInfo = new RepoItemInfo(this, "InputPassword", ".//input[@id='input-password']", "element", 30000, null, "4b8ccd5f-f761-4579-afc6-ea1c08e7f8b0");
                _clicksubmitbuttonInfo = new RepoItemInfo(this, "ClickSubmitButton", ".//button[@type='submit']", "element", 30000, null, "985d9302-eee1-444f-8f71-b9e46e285060");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a75c7191-3d25-4d92-bf61-ca3ad44ecb5e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputName item.
            /// </summary>
            [RepositoryItem("7182fbe0-c304-4bb8-ad99-8cbbbfcfccef")]
            public virtual Ranorex.InputTag InputName
            {
                get
                {
                    return _inputnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputName item info.
            /// </summary>
            [RepositoryItemInfo("7182fbe0-c304-4bb8-ad99-8cbbbfcfccef")]
            public virtual RepoItemInfo InputNameInfo
            {
                get
                {
                    return _inputnameInfo;
                }
            }

            /// <summary>
            /// The InputPassword item.
            /// </summary>
            [RepositoryItem("4b8ccd5f-f761-4579-afc6-ea1c08e7f8b0")]
            public virtual Ranorex.InputTag InputPassword
            {
                get
                {
                    return _inputpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPassword item info.
            /// </summary>
            [RepositoryItemInfo("4b8ccd5f-f761-4579-afc6-ea1c08e7f8b0")]
            public virtual RepoItemInfo InputPasswordInfo
            {
                get
                {
                    return _inputpasswordInfo;
                }
            }

            /// <summary>
            /// The ClickSubmitButton item.
            /// </summary>
            [RepositoryItem("985d9302-eee1-444f-8f71-b9e46e285060")]
            public virtual Ranorex.Button ClickSubmitButton
            {
                get
                {
                    return _clicksubmitbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ClickSubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("985d9302-eee1-444f-8f71-b9e46e285060")]
            public virtual RepoItemInfo ClickSubmitButtonInfo
            {
                get
                {
                    return _clicksubmitbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ProfileFolder folder.
        /// </summary>
        [RepositoryFolder("a40e102f-ce3a-4343-bcff-b804047e7eaa")]
        public partial class ProfileFolder : RepoGenBaseFolder
        {
            RepoItemInfo _profileInfo;
            RepoItemInfo _avatarInfo;

            /// <summary>
            /// Creates a new Profile  folder.
            /// </summary>
            public ProfileFolder(RepoGenBaseFolder parentFolder) :
                    base("Profile", "", parentFolder, 0, null, false, "a40e102f-ce3a-4343-bcff-b804047e7eaa", "")
            {
                _profileInfo = new RepoItemInfo(this, "Profile", ".//a[@innertext='Auto Auto ']", "element", 30000, null, "e3bd463d-a1f9-4dde-bfec-00f369c890d1");
                _avatarInfo = new RepoItemInfo(this, "Avatar", ".//img[@title='auto']", "element", 30000, null, "13c80e91-969a-4bc8-8c35-1b7de991b2ca");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a40e102f-ce3a-4343-bcff-b804047e7eaa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Profile item.
            /// </summary>
            [RepositoryItem("e3bd463d-a1f9-4dde-bfec-00f369c890d1")]
            public virtual Ranorex.ATag Profile
            {
                get
                {
                    return _profileInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Profile item info.
            /// </summary>
            [RepositoryItemInfo("e3bd463d-a1f9-4dde-bfec-00f369c890d1")]
            public virtual RepoItemInfo ProfileInfo
            {
                get
                {
                    return _profileInfo;
                }
            }

            /// <summary>
            /// The Avatar item.
            /// </summary>
            [RepositoryItem("13c80e91-969a-4bc8-8c35-1b7de991b2ca")]
            public virtual Ranorex.ImgTag Avatar
            {
                get
                {
                    return _avatarInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Avatar item info.
            /// </summary>
            [RepositoryItemInfo("13c80e91-969a-4bc8-8c35-1b7de991b2ca")]
            public virtual RepoItemInfo AvatarInfo
            {
                get
                {
                    return _avatarInfo;
                }
            }
        }

        /// <summary>
        /// The DashboardFolder folder.
        /// </summary>
        [RepositoryFolder("2e537fe2-5dfd-47d7-8b93-6de6bd32d3b5")]
        public partial class DashboardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _atagmenucatalogInfo;
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new Dashboard  folder.
            /// </summary>
            public DashboardFolder(RepoGenBaseFolder parentFolder) :
                    base("Dashboard", "", parentFolder, 0, null, false, "2e537fe2-5dfd-47d7-8b93-6de6bd32d3b5", "")
            {
                _atagmenucatalogInfo = new RepoItemInfo(this, "ATagMenuCatalog", ".//li[@id<'menu-'+$Menu_items]", "", 30000, null, "ee83cfd2-9220-4307-92a7-1545a3e5f64c");
                _newitemInfo = new RepoItemInfo(this, "NewItem", ".//li[#'menu-catalog']/a[@innertext=' Catalog']", ".//li[#'menu-catalog']/a[@innertext=' Catalog']", 30000, null, "993d6cd2-3b7d-4450-9ade-e3e8e82b3330");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2e537fe2-5dfd-47d7-8b93-6de6bd32d3b5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ATagMenuCatalog item.
            /// </summary>
            [RepositoryItem("ee83cfd2-9220-4307-92a7-1545a3e5f64c")]
            public virtual Ranorex.LiTag ATagMenuCatalog
            {
                get
                {
                    return _atagmenucatalogInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The ATagMenuCatalog item info.
            /// </summary>
            [RepositoryItemInfo("ee83cfd2-9220-4307-92a7-1545a3e5f64c")]
            public virtual RepoItemInfo ATagMenuCatalogInfo
            {
                get
                {
                    return _atagmenucatalogInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("993d6cd2-3b7d-4450-9ade-e3e8e82b3330")]
            public virtual Ranorex.ATag NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("993d6cd2-3b7d-4450-9ade-e3e8e82b3330")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }
        }

        /// <summary>
        /// The LogoutPageFolder folder.
        /// </summary>
        [RepositoryFolder("ccd151c2-bef1-453f-9f43-6fd4798a0144")]
        public partial class LogoutPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _spanlogoutInfo;

            /// <summary>
            /// Creates a new LogoutPage  folder.
            /// </summary>
            public LogoutPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LogoutPage", "", parentFolder, 0, null, false, "ccd151c2-bef1-453f-9f43-6fd4798a0144", "")
            {
                _spanlogoutInfo = new RepoItemInfo(this, "spanLogout", ".//span[@innertext='Logout']", "element", 30000, null, "3cffb199-a1e5-44fc-9d17-46d7aff2f36e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ccd151c2-bef1-453f-9f43-6fd4798a0144")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The spanLogout item.
            /// </summary>
            [RepositoryItem("3cffb199-a1e5-44fc-9d17-46d7aff2f36e")]
            public virtual Ranorex.SpanTag spanLogout
            {
                get
                {
                    return _spanlogoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The spanLogout item info.
            /// </summary>
            [RepositoryItemInfo("3cffb199-a1e5-44fc-9d17-46d7aff2f36e")]
            public virtual RepoItemInfo spanLogoutInfo
            {
                get
                {
                    return _spanlogoutInfo;
                }
            }
        }

        /// <summary>
        /// The NavigationFolder folder.
        /// </summary>
        [RepositoryFolder("8573a4d7-4ef9-4099-a278-3c38386bd62c")]
        public partial class NavigationFolder : RepoGenBaseFolder
        {
            MBA_WEBRepositoryFolders.ChildItemFolder _childitem;
            MBA_WEBRepositoryFolders.CatalogItemFolder _catalogitem;
            RepoItemInfo _hrefparentmenuInfo;
            RepoItemInfo _ulmenudroplistInfo;

            /// <summary>
            /// Creates a new Navigation  folder.
            /// </summary>
            public NavigationFolder(RepoGenBaseFolder parentFolder) :
                    base("Navigation", "", parentFolder, 0, null, false, "8573a4d7-4ef9-4099-a278-3c38386bd62c", "")
            {
                _childitem = new MBA_WEBRepositoryFolders.ChildItemFolder(this);
                _catalogitem = new MBA_WEBRepositoryFolders.CatalogItemFolder(this);
                _hrefparentmenuInfo = new RepoItemInfo(this, "hrefParentMenu", ".//a[@innertext<$Menu_Items]", "element", 30000, null, "11b8993d-bcb8-4293-b8b7-48c69903ef32");
                _ulmenudroplistInfo = new RepoItemInfo(this, "ulMenuDropList", ".//a[@innertext<$Menu_Items]/following-sibling::ul[@class='collapse in']", "element", 30000, null, "6ab5b2c7-9b9c-4386-a2f3-dbe7e3bf81d9");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8573a4d7-4ef9-4099-a278-3c38386bd62c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The hrefParentMenu item.
            /// </summary>
            [RepositoryItem("11b8993d-bcb8-4293-b8b7-48c69903ef32")]
            public virtual Ranorex.ATag hrefParentMenu
            {
                get
                {
                    return _hrefparentmenuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The hrefParentMenu item info.
            /// </summary>
            [RepositoryItemInfo("11b8993d-bcb8-4293-b8b7-48c69903ef32")]
            public virtual RepoItemInfo hrefParentMenuInfo
            {
                get
                {
                    return _hrefparentmenuInfo;
                }
            }

            /// <summary>
            /// The ulMenuDropList item.
            /// </summary>
            [RepositoryItem("6ab5b2c7-9b9c-4386-a2f3-dbe7e3bf81d9")]
            public virtual Ranorex.UlTag ulMenuDropList
            {
                get
                {
                    return _ulmenudroplistInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The ulMenuDropList item info.
            /// </summary>
            [RepositoryItemInfo("6ab5b2c7-9b9c-4386-a2f3-dbe7e3bf81d9")]
            public virtual RepoItemInfo ulMenuDropListInfo
            {
                get
                {
                    return _ulmenudroplistInfo;
                }
            }

            /// <summary>
            /// The ChildItem folder.
            /// </summary>
            [RepositoryFolder("33853b5f-9723-49fa-a0b7-5530c5e55dec")]
            public virtual MBA_WEBRepositoryFolders.ChildItemFolder ChildItem
            {
                get { return _childitem; }
            }

            /// <summary>
            /// The CatalogItem folder.
            /// </summary>
            [RepositoryFolder("3e546979-be64-42cd-8a1a-2100f9da424c")]
            public virtual MBA_WEBRepositoryFolders.CatalogItemFolder CatalogItem
            {
                get { return _catalogitem; }
            }
        }

        /// <summary>
        /// The ChildItemFolder folder.
        /// </summary>
        [RepositoryFolder("33853b5f-9723-49fa-a0b7-5530c5e55dec")]
        public partial class ChildItemFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hrefchildmenuInfo;

            /// <summary>
            /// Creates a new ChildItem  folder.
            /// </summary>
            public ChildItemFolder(RepoGenBaseFolder parentFolder) :
                    base("ChildItem", "", parentFolder, 0, null, false, "33853b5f-9723-49fa-a0b7-5530c5e55dec", "")
            {
                _hrefchildmenuInfo = new RepoItemInfo(this, "hrefChildMenu", ".//a[@innertext=$Item]", "", 30000, null, "303ee847-935b-4e13-ad02-c0de8431d138");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("33853b5f-9723-49fa-a0b7-5530c5e55dec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The hrefChildMenu item.
            /// </summary>
            [RepositoryItem("303ee847-935b-4e13-ad02-c0de8431d138")]
            public virtual Ranorex.ATag hrefChildMenu
            {
                get
                {
                    return _hrefchildmenuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The hrefChildMenu item info.
            /// </summary>
            [RepositoryItemInfo("303ee847-935b-4e13-ad02-c0de8431d138")]
            public virtual RepoItemInfo hrefChildMenuInfo
            {
                get
                {
                    return _hrefchildmenuInfo;
                }
            }
        }

        /// <summary>
        /// The CatalogItemFolder folder.
        /// </summary>
        [RepositoryFolder("3e546979-be64-42cd-8a1a-2100f9da424c")]
        public partial class CatalogItemFolder : RepoGenBaseFolder
        {
            MBA_WEBRepositoryFolders.ProductsFolder _products;

            /// <summary>
            /// Creates a new CatalogItem  folder.
            /// </summary>
            public CatalogItemFolder(RepoGenBaseFolder parentFolder) :
                    base("CatalogItem", "", parentFolder, 0, null, false, "3e546979-be64-42cd-8a1a-2100f9da424c", "")
            {
                _products = new MBA_WEBRepositoryFolders.ProductsFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3e546979-be64-42cd-8a1a-2100f9da424c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Products folder.
            /// </summary>
            [RepositoryFolder("95cd6e2f-f481-4edf-8e63-b5d30a64afe5")]
            public virtual MBA_WEBRepositoryFolders.ProductsFolder Products
            {
                get { return _products; }
            }
        }

        /// <summary>
        /// The ProductsFolder folder.
        /// </summary>
        [RepositoryFolder("95cd6e2f-f481-4edf-8e63-b5d30a64afe5")]
        public partial class ProductsFolder : RepoGenBaseFolder
        {
            MBA_WEBRepositoryFolders.AddProductFolder _addproduct;
            MBA_WEBRepositoryFolders.ProductFilterFolder _productfilter;
            MBA_WEBRepositoryFolders.ProductListFolder _productlist;
            RepoItemInfo _hrefaddnewInfo;

            /// <summary>
            /// Creates a new Products  folder.
            /// </summary>
            public ProductsFolder(RepoGenBaseFolder parentFolder) :
                    base("Products", "", parentFolder, 0, null, false, "95cd6e2f-f481-4edf-8e63-b5d30a64afe5", "")
            {
                _addproduct = new MBA_WEBRepositoryFolders.AddProductFolder(this);
                _productfilter = new MBA_WEBRepositoryFolders.ProductFilterFolder(this);
                _productlist = new MBA_WEBRepositoryFolders.ProductListFolder(this);
                _hrefaddnewInfo = new RepoItemInfo(this, "hrefAddNew", ".//a[@data-original-title='Add New']", "element", 30000, null, "9b010e5d-420b-4135-b20d-8a76a89e8d44");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("95cd6e2f-f481-4edf-8e63-b5d30a64afe5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The hrefAddNew item.
            /// </summary>
            [RepositoryItem("9b010e5d-420b-4135-b20d-8a76a89e8d44")]
            public virtual Ranorex.ATag hrefAddNew
            {
                get
                {
                    return _hrefaddnewInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The hrefAddNew item info.
            /// </summary>
            [RepositoryItemInfo("9b010e5d-420b-4135-b20d-8a76a89e8d44")]
            public virtual RepoItemInfo hrefAddNewInfo
            {
                get
                {
                    return _hrefaddnewInfo;
                }
            }

            /// <summary>
            /// The AddProduct folder.
            /// </summary>
            [RepositoryFolder("b900080c-792a-456f-bb6a-c38022704088")]
            public virtual MBA_WEBRepositoryFolders.AddProductFolder AddProduct
            {
                get { return _addproduct; }
            }

            /// <summary>
            /// The ProductFilter folder.
            /// </summary>
            [RepositoryFolder("759f13a0-b7fb-478e-9d8f-5b03b49d9405")]
            public virtual MBA_WEBRepositoryFolders.ProductFilterFolder ProductFilter
            {
                get { return _productfilter; }
            }

            /// <summary>
            /// The ProductList folder.
            /// </summary>
            [RepositoryFolder("59d9812c-931e-4a2f-b84d-e0719d1335f8")]
            public virtual MBA_WEBRepositoryFolders.ProductListFolder ProductList
            {
                get { return _productlist; }
            }
        }

        /// <summary>
        /// The AddProductFolder folder.
        /// </summary>
        [RepositoryFolder("b900080c-792a-456f-bb6a-c38022704088")]
        public partial class AddProductFolder : RepoGenBaseFolder
        {
            MBA_WEBRepositoryFolders.LinkTabFolder _linktab;
            MBA_WEBRepositoryFolders.DataTabFolder _datatab;
            MBA_WEBRepositoryFolders.GeneralTabFolder _generaltab;
            RepoItemInfo _btnsubmitInfo;

            /// <summary>
            /// Creates a new AddProduct  folder.
            /// </summary>
            public AddProductFolder(RepoGenBaseFolder parentFolder) :
                    base("AddProduct", "", parentFolder, 0, null, false, "b900080c-792a-456f-bb6a-c38022704088", "")
            {
                _linktab = new MBA_WEBRepositoryFolders.LinkTabFolder(this);
                _datatab = new MBA_WEBRepositoryFolders.DataTabFolder(this);
                _generaltab = new MBA_WEBRepositoryFolders.GeneralTabFolder(this);
                _btnsubmitInfo = new RepoItemInfo(this, "BtnSubmit", ".//button[@type='submit']", "element", 30000, null, "56ff5e14-9906-4c74-a653-b6ea83f0d53b");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b900080c-792a-456f-bb6a-c38022704088")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnSubmit item.
            /// </summary>
            [RepositoryItem("56ff5e14-9906-4c74-a653-b6ea83f0d53b")]
            public virtual Ranorex.Button BtnSubmit
            {
                get
                {
                    return _btnsubmitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("56ff5e14-9906-4c74-a653-b6ea83f0d53b")]
            public virtual RepoItemInfo BtnSubmitInfo
            {
                get
                {
                    return _btnsubmitInfo;
                }
            }

            /// <summary>
            /// The LinkTab folder.
            /// </summary>
            [RepositoryFolder("9a510cd1-7e1c-41b2-b7f7-f05ccb606479")]
            public virtual MBA_WEBRepositoryFolders.LinkTabFolder LinkTab
            {
                get { return _linktab; }
            }

            /// <summary>
            /// The DataTab folder.
            /// </summary>
            [RepositoryFolder("1548d5b0-bb8a-4482-9a73-15d8d5492f37")]
            public virtual MBA_WEBRepositoryFolders.DataTabFolder DataTab
            {
                get { return _datatab; }
            }

            /// <summary>
            /// The GeneralTab folder.
            /// </summary>
            [RepositoryFolder("5ed1ac33-896e-4bcf-9252-681614d1a0b3")]
            public virtual MBA_WEBRepositoryFolders.GeneralTabFolder GeneralTab
            {
                get { return _generaltab; }
            }
        }

        /// <summary>
        /// The LinkTabFolder folder.
        /// </summary>
        [RepositoryFolder("9a510cd1-7e1c-41b2-b7f7-f05ccb606479")]
        public partial class LinkTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hreflinktabInfo;
            RepoItemInfo _newitem1Info;

            /// <summary>
            /// Creates a new LinkTab  folder.
            /// </summary>
            public LinkTabFolder(RepoGenBaseFolder parentFolder) :
                    base("LinkTab", "", parentFolder, 0, null, false, "9a510cd1-7e1c-41b2-b7f7-f05ccb606479", "")
            {
                _hreflinktabInfo = new RepoItemInfo(this, "hrefLinkTab", ".//a[@innertext='Links']", "element", 30000, null, "ef96e5d5-68ec-4c76-9ae5-bcc8420eb38e");
                _newitem1Info = new RepoItemInfo(this, "NewItem1", ".//label[@innertext~'Default']/input", "element", 30000, null, "d99bb24b-d282-471e-a239-83c3f691f80c");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9a510cd1-7e1c-41b2-b7f7-f05ccb606479")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The hrefLinkTab item.
            /// </summary>
            [RepositoryItem("ef96e5d5-68ec-4c76-9ae5-bcc8420eb38e")]
            public virtual Ranorex.ATag hrefLinkTab
            {
                get
                {
                    return _hreflinktabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The hrefLinkTab item info.
            /// </summary>
            [RepositoryItemInfo("ef96e5d5-68ec-4c76-9ae5-bcc8420eb38e")]
            public virtual RepoItemInfo hrefLinkTabInfo
            {
                get
                {
                    return _hreflinktabInfo;
                }
            }

            /// <summary>
            /// The NewItem1 item.
            /// </summary>
            [RepositoryItem("d99bb24b-d282-471e-a239-83c3f691f80c")]
            public virtual Ranorex.InputTag NewItem1
            {
                get
                {
                    return _newitem1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NewItem1 item info.
            /// </summary>
            [RepositoryItemInfo("d99bb24b-d282-471e-a239-83c3f691f80c")]
            public virtual RepoItemInfo NewItem1Info
            {
                get
                {
                    return _newitem1Info;
                }
            }
        }

        /// <summary>
        /// The DataTabFolder folder.
        /// </summary>
        [RepositoryFolder("1548d5b0-bb8a-4482-9a73-15d8d5492f37")]
        public partial class DataTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputmodelInfo;
            RepoItemInfo _inputpriceInfo;
            RepoItemInfo _inputstartdateInfo;
            RepoItemInfo _inputenddateInfo;
            RepoItemInfo _hrefdatatabInfo;

            /// <summary>
            /// Creates a new DataTab  folder.
            /// </summary>
            public DataTabFolder(RepoGenBaseFolder parentFolder) :
                    base("DataTab", "", parentFolder, 0, null, false, "1548d5b0-bb8a-4482-9a73-15d8d5492f37", "")
            {
                _inputmodelInfo = new RepoItemInfo(this, "inputModel", ".//input[@id='input-model']", "element", 30000, null, "9f4eebc8-4846-45d5-848c-62a87940cbb6");
                _inputpriceInfo = new RepoItemInfo(this, "inputPrice", ".//input[@id='input-price']", "element", 30000, null, "abe89477-730f-4989-bacc-97bcb449096b");
                _inputstartdateInfo = new RepoItemInfo(this, "inputStartDate", ".//input[@name='date_available']", "element", 30000, null, "884d4ebf-af05-4ce6-a731-88d4f80f1e82");
                _inputenddateInfo = new RepoItemInfo(this, "inputEndDate", ".//input[@name='end_date_available']", "element", 30000, null, "442d6356-fcaa-4a7f-8d9b-396c34e79289");
                _hrefdatatabInfo = new RepoItemInfo(this, "hrefDataTab", ".//a[@innertext='Data']", "element", 30000, null, "28e09277-2316-4be0-a5b9-bea14e587526");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1548d5b0-bb8a-4482-9a73-15d8d5492f37")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The inputModel item.
            /// </summary>
            [RepositoryItem("9f4eebc8-4846-45d5-848c-62a87940cbb6")]
            public virtual Ranorex.InputTag inputModel
            {
                get
                {
                    return _inputmodelInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The inputModel item info.
            /// </summary>
            [RepositoryItemInfo("9f4eebc8-4846-45d5-848c-62a87940cbb6")]
            public virtual RepoItemInfo inputModelInfo
            {
                get
                {
                    return _inputmodelInfo;
                }
            }

            /// <summary>
            /// The inputPrice item.
            /// </summary>
            [RepositoryItem("abe89477-730f-4989-bacc-97bcb449096b")]
            public virtual Ranorex.InputTag inputPrice
            {
                get
                {
                    return _inputpriceInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The inputPrice item info.
            /// </summary>
            [RepositoryItemInfo("abe89477-730f-4989-bacc-97bcb449096b")]
            public virtual RepoItemInfo inputPriceInfo
            {
                get
                {
                    return _inputpriceInfo;
                }
            }

            /// <summary>
            /// The inputStartDate item.
            /// </summary>
            [RepositoryItem("884d4ebf-af05-4ce6-a731-88d4f80f1e82")]
            public virtual Ranorex.InputTag inputStartDate
            {
                get
                {
                    return _inputstartdateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The inputStartDate item info.
            /// </summary>
            [RepositoryItemInfo("884d4ebf-af05-4ce6-a731-88d4f80f1e82")]
            public virtual RepoItemInfo inputStartDateInfo
            {
                get
                {
                    return _inputstartdateInfo;
                }
            }

            /// <summary>
            /// The inputEndDate item.
            /// </summary>
            [RepositoryItem("442d6356-fcaa-4a7f-8d9b-396c34e79289")]
            public virtual Ranorex.InputTag inputEndDate
            {
                get
                {
                    return _inputenddateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The inputEndDate item info.
            /// </summary>
            [RepositoryItemInfo("442d6356-fcaa-4a7f-8d9b-396c34e79289")]
            public virtual RepoItemInfo inputEndDateInfo
            {
                get
                {
                    return _inputenddateInfo;
                }
            }

            /// <summary>
            /// The hrefDataTab item.
            /// </summary>
            [RepositoryItem("28e09277-2316-4be0-a5b9-bea14e587526")]
            public virtual Ranorex.ATag hrefDataTab
            {
                get
                {
                    return _hrefdatatabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The hrefDataTab item info.
            /// </summary>
            [RepositoryItemInfo("28e09277-2316-4be0-a5b9-bea14e587526")]
            public virtual RepoItemInfo hrefDataTabInfo
            {
                get
                {
                    return _hrefdatatabInfo;
                }
            }
        }

        /// <summary>
        /// The GeneralTabFolder folder.
        /// </summary>
        [RepositoryFolder("5ed1ac33-896e-4bcf-9252-681614d1a0b3")]
        public partial class GeneralTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputproductnameInfo;
            RepoItemInfo _inputmetatagInfo;
            RepoItemInfo _hrefgeneraltabInfo;

            /// <summary>
            /// Creates a new GeneralTab  folder.
            /// </summary>
            public GeneralTabFolder(RepoGenBaseFolder parentFolder) :
                    base("GeneralTab", "", parentFolder, 0, null, false, "5ed1ac33-896e-4bcf-9252-681614d1a0b3", "")
            {
                _inputproductnameInfo = new RepoItemInfo(this, "inputProductName", ".//input[@id='input-name1']", "element", 30000, null, "41e576a7-80c1-4e3d-8110-d0e97664e74a");
                _inputmetatagInfo = new RepoItemInfo(this, "inputMetaTag", ".//input[@id='input-meta-title1']", "element", 30000, null, "70e6fa97-a914-45a6-8e21-450ffe5bd483");
                _hrefgeneraltabInfo = new RepoItemInfo(this, "hrefGeneralTab", ".//a[@innertext='General']", "element", 30000, null, "ead41199-4749-40e9-b9b2-16fca3fdea66");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5ed1ac33-896e-4bcf-9252-681614d1a0b3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The inputProductName item.
            /// </summary>
            [RepositoryItem("41e576a7-80c1-4e3d-8110-d0e97664e74a")]
            public virtual Ranorex.InputTag inputProductName
            {
                get
                {
                    return _inputproductnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The inputProductName item info.
            /// </summary>
            [RepositoryItemInfo("41e576a7-80c1-4e3d-8110-d0e97664e74a")]
            public virtual RepoItemInfo inputProductNameInfo
            {
                get
                {
                    return _inputproductnameInfo;
                }
            }

            /// <summary>
            /// The inputMetaTag item.
            /// </summary>
            [RepositoryItem("70e6fa97-a914-45a6-8e21-450ffe5bd483")]
            public virtual Ranorex.InputTag inputMetaTag
            {
                get
                {
                    return _inputmetatagInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The inputMetaTag item info.
            /// </summary>
            [RepositoryItemInfo("70e6fa97-a914-45a6-8e21-450ffe5bd483")]
            public virtual RepoItemInfo inputMetaTagInfo
            {
                get
                {
                    return _inputmetatagInfo;
                }
            }

            /// <summary>
            /// The hrefGeneralTab item.
            /// </summary>
            [RepositoryItem("ead41199-4749-40e9-b9b2-16fca3fdea66")]
            public virtual Ranorex.ATag hrefGeneralTab
            {
                get
                {
                    return _hrefgeneraltabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The hrefGeneralTab item info.
            /// </summary>
            [RepositoryItemInfo("ead41199-4749-40e9-b9b2-16fca3fdea66")]
            public virtual RepoItemInfo hrefGeneralTabInfo
            {
                get
                {
                    return _hrefgeneraltabInfo;
                }
            }
        }

        /// <summary>
        /// The ProductFilterFolder folder.
        /// </summary>
        [RepositoryFolder("759f13a0-b7fb-478e-9d8f-5b03b49d9405")]
        public partial class ProductFilterFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputproductnameInfo;
            RepoItemInfo _inputmodelInfo;
            RepoItemInfo _btnfilterInfo;

            /// <summary>
            /// Creates a new ProductFilter  folder.
            /// </summary>
            public ProductFilterFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductFilter", "", parentFolder, 0, null, false, "759f13a0-b7fb-478e-9d8f-5b03b49d9405", "")
            {
                _inputproductnameInfo = new RepoItemInfo(this, "inputProductName", ".//input[@name='filter_name']", "element", 30000, null, "934a4e8f-38c8-4fd9-846a-8e15a13fdc48");
                _inputmodelInfo = new RepoItemInfo(this, "inputModel", ".//input[@name='filter_model']", "element", 30000, null, "2344dd94-cd4d-4b92-a02c-9532d01fc39d");
                _btnfilterInfo = new RepoItemInfo(this, "BtnFilter", ".//button[@id='button-filter']", "element", 30000, null, "dcf09922-5e81-4d85-a19a-65beb3ae9a12");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("759f13a0-b7fb-478e-9d8f-5b03b49d9405")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The inputProductName item.
            /// </summary>
            [RepositoryItem("934a4e8f-38c8-4fd9-846a-8e15a13fdc48")]
            public virtual Ranorex.InputTag inputProductName
            {
                get
                {
                    return _inputproductnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The inputProductName item info.
            /// </summary>
            [RepositoryItemInfo("934a4e8f-38c8-4fd9-846a-8e15a13fdc48")]
            public virtual RepoItemInfo inputProductNameInfo
            {
                get
                {
                    return _inputproductnameInfo;
                }
            }

            /// <summary>
            /// The inputModel item.
            /// </summary>
            [RepositoryItem("2344dd94-cd4d-4b92-a02c-9532d01fc39d")]
            public virtual Ranorex.InputTag inputModel
            {
                get
                {
                    return _inputmodelInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The inputModel item info.
            /// </summary>
            [RepositoryItemInfo("2344dd94-cd4d-4b92-a02c-9532d01fc39d")]
            public virtual RepoItemInfo inputModelInfo
            {
                get
                {
                    return _inputmodelInfo;
                }
            }

            /// <summary>
            /// The BtnFilter item.
            /// </summary>
            [RepositoryItem("dcf09922-5e81-4d85-a19a-65beb3ae9a12")]
            public virtual Ranorex.Button BtnFilter
            {
                get
                {
                    return _btnfilterInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnFilter item info.
            /// </summary>
            [RepositoryItemInfo("dcf09922-5e81-4d85-a19a-65beb3ae9a12")]
            public virtual RepoItemInfo BtnFilterInfo
            {
                get
                {
                    return _btnfilterInfo;
                }
            }
        }

        /// <summary>
        /// The ProductListFolder folder.
        /// </summary>
        [RepositoryFolder("59d9812c-931e-4a2f-b84d-e0719d1335f8")]
        public partial class ProductListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tbodyproducttableInfo;
            RepoItemInfo _hrefnextpageInfo;

            /// <summary>
            /// Creates a new ProductList  folder.
            /// </summary>
            public ProductListFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductList", "", parentFolder, 0, null, false, "59d9812c-931e-4a2f-b84d-e0719d1335f8", "")
            {
                _tbodyproducttableInfo = new RepoItemInfo(this, "tbodyProductTable", ".//div[@class='table-responsive']//descendant::tbody", "element", 30000, null, "6e285105-c02f-497a-8e50-f30e3953785d");
                _hrefnextpageInfo = new RepoItemInfo(this, "hrefNextPage", ".//a[@class='next']", "element", 30000, null, "3b1a83f7-5037-417f-9ccc-98b5e5ba9f18");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("59d9812c-931e-4a2f-b84d-e0719d1335f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The tbodyProductTable item.
            /// </summary>
            [RepositoryItem("6e285105-c02f-497a-8e50-f30e3953785d")]
            public virtual Ranorex.TBodyTag tbodyProductTable
            {
                get
                {
                    return _tbodyproducttableInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The tbodyProductTable item info.
            /// </summary>
            [RepositoryItemInfo("6e285105-c02f-497a-8e50-f30e3953785d")]
            public virtual RepoItemInfo tbodyProductTableInfo
            {
                get
                {
                    return _tbodyproducttableInfo;
                }
            }

            /// <summary>
            /// The hrefNextPage item.
            /// </summary>
            [RepositoryItem("3b1a83f7-5037-417f-9ccc-98b5e5ba9f18")]
            public virtual Ranorex.ATag hrefNextPage
            {
                get
                {
                    return _hrefnextpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The hrefNextPage item info.
            /// </summary>
            [RepositoryItemInfo("3b1a83f7-5037-417f-9ccc-98b5e5ba9f18")]
            public virtual RepoItemInfo hrefNextPageInfo
            {
                get
                {
                    return _hrefnextpageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
