///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MBATest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MBATestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b28f6d7c-4143-4471-82b9-e6b6b62d7a38")]
    public partial class MBATestRepository : RepoGenBaseFolder
    {
        static MBATestRepository instance = new MBATestRepository();
        MBATestRepositoryFolders.AdministrationAppFolder _administration;
        MBATestRepositoryFolders.SavePasswordAppFolder _savepassword;
        MBATestRepositoryFolders.MBATestAppFolder _mbatest;

        /// <summary>
        /// Gets the singleton class instance representing the MBATestRepository element repository.
        /// </summary>
        [RepositoryFolder("b28f6d7c-4143-4471-82b9-e6b6b62d7a38")]
        public static MBATestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MBATestRepository() 
            : base("MBATestRepository", "/", null, 0, false, "b28f6d7c-4143-4471-82b9-e6b6b62d7a38", ".\\RepositoryImages\\MBATestRepositoryb28f6d7c.rximgres")
        {
            _administration = new MBATestRepositoryFolders.AdministrationAppFolder(this);
            _savepassword = new MBATestRepositoryFolders.SavePasswordAppFolder(this);
            _mbatest = new MBATestRepositoryFolders.MBATestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b28f6d7c-4143-4471-82b9-e6b6b62d7a38")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Administration folder.
        /// </summary>
        [RepositoryFolder("54a5c4f0-b406-4a97-8b25-2e7e7c86ced4")]
        public virtual MBATestRepositoryFolders.AdministrationAppFolder Administration
        {
            get { return _administration; }
        }

        /// <summary>
        /// The SavePassword folder.
        /// </summary>
        [RepositoryFolder("644d0a5c-02ba-49ae-9009-8e522c08c09e")]
        public virtual MBATestRepositoryFolders.SavePasswordAppFolder SavePassword
        {
            get { return _savepassword; }
        }

        /// <summary>
        /// The MBATest folder.
        /// </summary>
        [RepositoryFolder("9f4d622e-36cc-4e52-8f06-addda7ef15f1")]
        public virtual MBATestRepositoryFolders.MBATestAppFolder MBATest
        {
            get { return _mbatest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MBATestRepositoryFolders
    {
        /// <summary>
        /// The AdministrationAppFolder folder.
        /// </summary>
        [RepositoryFolder("54a5c4f0-b406-4a97-8b25-2e7e7c86ced4")]
        public partial class AdministrationAppFolder : RepoGenBaseFolder
        {
            MBATestRepositoryFolders.NavNavbarNavNavbarRightFolder _navnavbarnavnavbarright;
            RepoItemInfo _inputusernameInfo;
            RepoItemInfo _inputpasswordInfo;
            RepoItemInfo _buttontagloginInfo;

            /// <summary>
            /// Creates a new Administration  folder.
            /// </summary>
            public AdministrationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Administration", "/dom[@domain='ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "54a5c4f0-b406-4a97-8b25-2e7e7c86ced4", "")
            {
                _navnavbarnavnavbarright = new MBATestRepositoryFolders.NavNavbarNavNavbarRightFolder(this);
                _inputusernameInfo = new RepoItemInfo(this, "InputUsername", ".//input[#'input-username']", ".//input[#'input-username']", 30000, null, "bbfbb8d9-cef3-4465-b423-2fe4ed71c3ef");
                _inputpasswordInfo = new RepoItemInfo(this, "InputPassword", ".//input[#'input-password']", ".//input[#'input-password']", 30000, null, "f2d6e679-e48e-4c34-bf5c-7f89603ee710");
                _buttontagloginInfo = new RepoItemInfo(this, "ButtonTagLogin", ".//div[#'content']/div/div//form[@action='https://ptn-test1.oc.mbasrv.com/sbe/index.php?route=common/login']/div[3]/button[@innertext=' Login']", ".//div[#'content']//button[@innertext=' Login']", 30000, null, "96e8035d-ca91-426f-abfa-afca5a7e4277");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("54a5c4f0-b406-4a97-8b25-2e7e7c86ced4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("54a5c4f0-b406-4a97-8b25-2e7e7c86ced4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputUsername item.
            /// </summary>
            [RepositoryItem("bbfbb8d9-cef3-4465-b423-2fe4ed71c3ef")]
            public virtual Ranorex.InputTag InputUsername
            {
                get
                {
                    return _inputusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputUsername item info.
            /// </summary>
            [RepositoryItemInfo("bbfbb8d9-cef3-4465-b423-2fe4ed71c3ef")]
            public virtual RepoItemInfo InputUsernameInfo
            {
                get
                {
                    return _inputusernameInfo;
                }
            }

            /// <summary>
            /// The InputPassword item.
            /// </summary>
            [RepositoryItem("f2d6e679-e48e-4c34-bf5c-7f89603ee710")]
            public virtual Ranorex.InputTag InputPassword
            {
                get
                {
                    return _inputpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPassword item info.
            /// </summary>
            [RepositoryItemInfo("f2d6e679-e48e-4c34-bf5c-7f89603ee710")]
            public virtual RepoItemInfo InputPasswordInfo
            {
                get
                {
                    return _inputpasswordInfo;
                }
            }

            /// <summary>
            /// The ButtonTagLogin item.
            /// </summary>
            [RepositoryItem("96e8035d-ca91-426f-abfa-afca5a7e4277")]
            public virtual Ranorex.ButtonTag ButtonTagLogin
            {
                get
                {
                    return _buttontagloginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagLogin item info.
            /// </summary>
            [RepositoryItemInfo("96e8035d-ca91-426f-abfa-afca5a7e4277")]
            public virtual RepoItemInfo ButtonTagLoginInfo
            {
                get
                {
                    return _buttontagloginInfo;
                }
            }

            /// <summary>
            /// The NavNavbarNavNavbarRight folder.
            /// </summary>
            [RepositoryFolder("fc69b142-db52-4f35-90c5-349d6b8cf178")]
            public virtual MBATestRepositoryFolders.NavNavbarNavNavbarRightFolder NavNavbarNavNavbarRight
            {
                get { return _navnavbarnavnavbarright; }
            }
        }

        /// <summary>
        /// The NavNavbarNavNavbarRightFolder folder.
        /// </summary>
        [RepositoryFolder("fc69b142-db52-4f35-90c5-349d6b8cf178")]
        public partial class NavNavbarNavNavbarRightFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fafacaretdownfafwInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _atagyourprofileInfo;

            /// <summary>
            /// Creates a new NavNavbarNavNavbarRight  folder.
            /// </summary>
            public NavNavbarNavNavbarRightFolder(RepoGenBaseFolder parentFolder) :
                    base("NavNavbarNavNavbarRight", ".//header[#'header']/?/?/ul", parentFolder, 30000, null, false, "fc69b142-db52-4f35-90c5-349d6b8cf178", "")
            {
                _fafacaretdownfafwInfo = new RepoItemInfo(this, "FaFaCaretDownFaFw", ".//i", "", 30000, null, "c506dd49-62ff-4bff-957a-4f9adc91690a");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//span[@innertext='Logout']", "", 30000, null, "6ddd9184-11b8-4518-acd1-62027b8cc3ac");
                _atagyourprofileInfo = new RepoItemInfo(this, "ATagYourProfile", "?/?/ul/?/?/a[@innertext=' Your Profile']", "", 30000, null, "b678a230-e9e8-4369-8619-4f25ec1bd9e9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fc69b142-db52-4f35-90c5-349d6b8cf178")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fc69b142-db52-4f35-90c5-349d6b8cf178")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FaFaCaretDownFaFw item.
            /// </summary>
            [RepositoryItem("c506dd49-62ff-4bff-957a-4f9adc91690a")]
            public virtual Ranorex.ITag FaFaCaretDownFaFw
            {
                get
                {
                    return _fafacaretdownfafwInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaCaretDownFaFw item info.
            /// </summary>
            [RepositoryItemInfo("c506dd49-62ff-4bff-957a-4f9adc91690a")]
            public virtual RepoItemInfo FaFaCaretDownFaFwInfo
            {
                get
                {
                    return _fafacaretdownfafwInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("6ddd9184-11b8-4518-acd1-62027b8cc3ac")]
            public virtual Ranorex.SpanTag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("6ddd9184-11b8-4518-acd1-62027b8cc3ac")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The ATagYourProfile item.
            /// </summary>
            [RepositoryItem("b678a230-e9e8-4369-8619-4f25ec1bd9e9")]
            public virtual Ranorex.ATag ATagYourProfile
            {
                get
                {
                    return _atagyourprofileInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagYourProfile item info.
            /// </summary>
            [RepositoryItemInfo("b678a230-e9e8-4369-8619-4f25ec1bd9e9")]
            public virtual RepoItemInfo ATagYourProfileInfo
            {
                get
                {
                    return _atagyourprofileInfo;
                }
            }
        }

        /// <summary>
        /// The SavePasswordAppFolder folder.
        /// </summary>
        [RepositoryFolder("644d0a5c-02ba-49ae-9009-8e522c08c09e")]
        public partial class SavePasswordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new SavePassword  folder.
            /// </summary>
            public SavePasswordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SavePassword", "/form[@title='Save password?']", parentFolder, 30000, null, true, "644d0a5c-02ba-49ae-9009-8e522c08c09e", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "element[@accessiblename='Save password?']//button[@accessiblename='Close']", ".//button[@accessiblename='Close']", 30000, null, "2ad06a50-ec89-4ca7-b4fe-9d6288494aeb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("644d0a5c-02ba-49ae-9009-8e522c08c09e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("644d0a5c-02ba-49ae-9009-8e522c08c09e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("2ad06a50-ec89-4ca7-b4fe-9d6288494aeb")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("2ad06a50-ec89-4ca7-b4fe-9d6288494aeb")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The MBATestAppFolder folder.
        /// </summary>
        [RepositoryFolder("9f4d622e-36cc-4e52-8f06-addda7ef15f1")]
        public partial class MBATestAppFolder : RepoGenBaseFolder
        {
            MBATestRepositoryFolders.LoginFolder _login;

            /// <summary>
            /// Creates a new MBATest  folder.
            /// </summary>
            public MBATestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MBATest", "/dom[@domain='ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "9f4d622e-36cc-4e52-8f06-addda7ef15f1", "")
            {
                _login = new MBATestRepositoryFolders.LoginFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9f4d622e-36cc-4e52-8f06-addda7ef15f1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9f4d622e-36cc-4e52-8f06-addda7ef15f1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login folder.
            /// </summary>
            [RepositoryFolder("16de99b2-381e-4a80-a5ad-392b8a33ef8c")]
            public virtual MBATestRepositoryFolders.LoginFolder Login
            {
                get { return _login; }
            }
        }

        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("16de99b2-381e-4a80-a5ad-392b8a33ef8c")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputusernameInfo;
            RepoItemInfo _inputpasswordInfo;
            RepoItemInfo _btnsubmitInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 30000, null, false, "16de99b2-381e-4a80-a5ad-392b8a33ef8c", "")
            {
                _inputusernameInfo = new RepoItemInfo(this, "InputUsername", ".//input[@name='username']", "element", 30000, null, "8471266a-1683-4e3a-b32c-dda0b9b4c186");
                _inputpasswordInfo = new RepoItemInfo(this, "InputPassword", ".//input[@name='password']", ".//input[#'input-password']", 30000, null, "fdee0fc2-c8c3-4997-896a-ad911315f02e");
                _btnsubmitInfo = new RepoItemInfo(this, "BtnSubmit", ".//button[@type='submit']", "element", 30000, null, "5472033b-3acf-46a0-b1f7-272dc089de7d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("16de99b2-381e-4a80-a5ad-392b8a33ef8c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("16de99b2-381e-4a80-a5ad-392b8a33ef8c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputUsername item.
            /// </summary>
            [RepositoryItem("8471266a-1683-4e3a-b32c-dda0b9b4c186")]
            public virtual Ranorex.InputTag InputUsername
            {
                get
                {
                    return _inputusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputUsername item info.
            /// </summary>
            [RepositoryItemInfo("8471266a-1683-4e3a-b32c-dda0b9b4c186")]
            public virtual RepoItemInfo InputUsernameInfo
            {
                get
                {
                    return _inputusernameInfo;
                }
            }

            /// <summary>
            /// The InputPassword item.
            /// </summary>
            [RepositoryItem("fdee0fc2-c8c3-4997-896a-ad911315f02e")]
            public virtual Ranorex.InputTag InputPassword
            {
                get
                {
                    return _inputpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPassword item info.
            /// </summary>
            [RepositoryItemInfo("fdee0fc2-c8c3-4997-896a-ad911315f02e")]
            public virtual RepoItemInfo InputPasswordInfo
            {
                get
                {
                    return _inputpasswordInfo;
                }
            }

            /// <summary>
            /// The BtnSubmit item.
            /// </summary>
            [RepositoryItem("5472033b-3acf-46a0-b1f7-272dc089de7d")]
            public virtual Ranorex.Button BtnSubmit
            {
                get
                {
                    return _btnsubmitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("5472033b-3acf-46a0-b1f7-272dc089de7d")]
            public virtual RepoItemInfo BtnSubmitInfo
            {
                get
                {
                    return _btnsubmitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
